development:
  adapter: postgresql
  database: foro_simple
  username: zubiefaber

test:
  adapter: postgresql
  database: foro_simple_test
  username: zubiefaber

production:
  adapter: postgresql
  database: foro_simple
  username: zubiefaber
